name: Build today ICS

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install requests icalendar

      - name: Run script
        env:
          ICS_URL: ${{ secrets.ICS_URL }}
        run: python filter_ics.py

      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          add: today.ics
          message: Update today ICS
